### ISSUE TITLE
Images don't use <g-image/> component

### ISSUE THREAD

**Issue by jmcmullen** [gridsome/gridsome-starter-markdown-blog#5]
By default in this starter images are loaded via an `<img>` tag, loosing one of Gridsome's best features as a result. 

Swapping to a `<g-image/>` like bellow results in the following error:
```html
<g-image :src="$page.blogPost.fields.image" :size="600"/>
```
```
[Vue warn]: Invalid prop: type check failed for prop "src". 
Expected Object, got String with value "images/imat-bagja-gumilar-518288-unsplash.jpg".
```

**Comment by mittalyashu** [comment]
Pull request from @bulbMe will resolve this issue https://github.com/gridsome/gridsome-starter-markdown-blog/pull/6
